name: Fetch Latest ArXiv Papers

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  fetch-papers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ArXiv Fetch Script
        env:
          ARXIV_OUTPUT_MODE: ${{ secrets.ARXIV_OUTPUT_MODE }}
          ARXIV_API_SERVICE_URL: ${{ secrets.ARXIV_API_SERVICE_URL }}
          ARXIV_ENABLE_AUTH: ${{ secrets.ARXIV_ENABLE_AUTH }}
          ARXIV_API_KEY: ${{ secrets.ARXIV_API_KEY }}
          FETCH_HOURS: '24'
        run: python3 arxiv_fetch.py
